require('dotenv').config()
const express   = require('express')
const mongoose  = require('mongoose')
const cors      = require('cors')
const helmet    = require('helmet')
const morgan    = require('morgan')
const rateLimit = require('express-rate-limit')

const authRoutes      = require('./routes/auth')
const productRoutes   = require('./routes/products')
const orderRoutes     = require('./routes/orders')
const paymentRoutes   = require('./routes/payments')
const vendorRoutes    = require('./routes/vendors')
const discountRoutes  = require('./routes/discounts')
const reviewRoutes    = require('./routes/reviews')
const adminRoutes     = require('./routes/admin')
const notifRoutes     = require('./routes/notifications')
const whatsappRoutes  = require('./routes/whatsapp')
const { searchRouter, shippingRouter, inventoryRouter, affiliateRouter, subscriptionRouter, loyaltyRouter, storefrontRouter, currencyRouter, feedRouter, appointmentRouter, aiPricingRouter } = require('./routes/extended')
const { startJobs } = require('./jobs/automation')

const app  = express()
const PORT = process.env.PORT || 5000

app.use(helmet({ contentSecurityPolicy: false }))
app.use(cors({ origin: [process.env.FRONTEND_URL || 'http://localhost:3000', /\.vercel\.app$/, /\.railway\.app$/], credentials: true }))
app.use('/api/auth', rateLimit({ windowMs: 15*60*1000, max: 20 }))
app.use('/api/', rateLimit({ windowMs: 15*60*1000, max: 500 }))
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'))
app.use(express.json({ limit: '10mb' }))
app.use(express.urlencoded({ extended: true, limit: '10mb' }))

app.get('/health', (req, res) => res.json({ ok: true, uptime: process.uptime() }))

app.use('/api/auth',          authRoutes)
app.use('/api/products',      productRoutes)
app.use('/api/orders',        orderRoutes)
app.use('/api/payments',      paymentRoutes)
app.use('/api/vendors',       vendorRoutes)
app.use('/api/discounts',     discountRoutes)
app.use('/api/reviews',       reviewRoutes)
app.use('/api/admin',         adminRoutes)
app.use('/api/notifications', notifRoutes)
app.use('/api/whatsapp',      whatsappRoutes)
app.use('/api/search',        searchRouter)
app.use('/api/shipping',      shippingRouter)
app.use('/api/inventory',     inventoryRouter)
app.use('/api/affiliate',     affiliateRouter)
app.use('/api/subscriptions', subscriptionRouter)
app.use('/api/loyalty',       loyaltyRouter)
app.use('/api/storefront',    storefrontRouter)
app.use('/api/currency',      currencyRouter)
app.use('/api/feed',          feedRouter)
app.use('/api/appointments',  appointmentRouter)
app.use('/api/ai-pricing',    aiPricingRouter)

app.post('/webhook/flutterwave', express.raw({ type: 'application/json' }), require('./routes/payments').handleWebhook)

app.use((err, req, res, next) => { console.error(err.stack); res.status(err.statusCode || 500).json({ success: false, message: err.message }) })
app.use((req, res) => res.status(404).json({ success: false, message: 'Not found' }))

mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 5000 })
  .then(() => { console.log('MongoDB connected'); app.listen(PORT, () => { console.log('ChatCart API port ' + PORT); startJobs() }) })
  .catch(err => { console.error('DB error:', err.message); process.exit(1) })

module.exports = app
